language: php
dist: trusty

php:
- 7.2
- 7.3
- 7.4
- nightly

env:
    - GUZZLE_VERSION=^6.3 UUID_VERSION=^3.8

matrix:
    fast_finish: true
    allow_failures:
    - php: nightly
    include:
        - php: 7.2
          env: GUZZLE_VERSION=^7.0 UUID_VERSION=^4.0
        - php: 7.2
          env: GUZZLE_VERSION=^7.0 UUID_VERSION=^4.0
        - php: 7.3
          env: GUZZLE_VERSION=^7.0 UUID_VERSION=^4.0
        - php: 7.4
          env: GUZZLE_VERSION=^7.0 UUID_VERSION=^4.0
        - php: nightly
          env: GUZZLE_VERSION=^7.0 UUID_VERSION=^4.0

sudo: false

cache:
    directories:
    - $HOME/.composer/cache

before_install:
    - composer require "guzzlehttp/guzzle:${GUZZLE_VERSION}" --no-update
    - composer require "ramsey/uuid:${UUID_VERSION}" --no-update

install:
- travis_retry composer install --no-interaction --no-suggest

script:
- composer validate --strict
- vendor/bin/phpunit --fail-on-risky
- vendor/bin/phpstan analyse --level 0 src tests